version: "3.7"

services:
  client:
    container_name: Client
    build:
      # context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 5173:5173 #external/internal ports
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true