version: "3.7"

services:
  server:
    container_name: Server
    build:
      # context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000 #external/internal ports
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true